### ISSUE TITLE
Compute precision, recall, and F1 on a hold-out test set

### ISSUE THREAD

**Issue by daynef** [gfreitag/Recipe-Project#8]
Let's measure the performance of our recipe extractor.  If you haven't already, set aside a portion of the data to be used for evaluation, and train your model on the rest.

For a more robust estimate of performance, you can try cross-validation.  Split the data into 5 portions ("folds") randomly, then run training and testing 5 times, each time training on 4/5 of the data and evaluating on the remaining 1/5.  Average the results across your five runs.

Try experimenting a little with training options to see how it impacts performance.  Can you find a configuration that outperforms the defaults?

**Comment by gfreitag** [comment]
I split the data up and trained with the five different folds, it ended up the average of the micro averages for all five was about 0.79098 and the average of the macro averages was 0.73372. The averages for the normal dataset is 0.8073 and 0.7957, which is slightly higher, but since the folds were very small(28 recipes in training and 7 recipes in testing) I'm not sure if their averages are reliable.

**Comment by gfreitag** [comment]
The Komninos word embeddings seem to take longer, but be much better on average for training.

**Comment by gfreitag** [comment]
Ok, true averages for f1 scores over five folds are 0.87628 for the micro average, and 0.85578 for the macro average. This is pretty good, my original score from my default test/train set was a bit lower(0.8415 and 0.8423).
